#!/bin/bash

# Phase 2A Rollout Script
# Deploy enhanced READMEs to remaining Personal Hub repositories

echo "🚀 Phase 2A Rollout: Personal Hub Repositories"
echo "=============================================="

if [ -z "$GITHUB_TOKEN" ]; then
    echo "❌ GITHUB_TOKEN not set. Please set it first:"
    echo "export GITHUB_TOKEN=\"your_token_here\""
    exit 1
fi

echo "✅ GitHub token is set"
echo ""

# Phase 2A repositories (excluding external-learning-platforms which is already deployed)
repositories=(
    "portfolio-website:DevPersonalHub"
    "technical-showcase:DevPersonalHub" 
    "learning-projects:DevPersonalHub"
)

total_repos=${#repositories[@]}
success_count=0
failure_count=0

echo "📋 Phase 2A Deployment Plan:"
echo "- portfolio-website (Professional portfolio and personal branding)"
echo "- technical-showcase (Technical experiments and innovation demonstrations)"
echo "- learning-projects (Knowledge base and learning project documentation)"
echo ""

for repo_entry in "${repositories[@]}"; do
    IFS=':' read -r repo_name org_name <<< "$repo_entry"
    
    echo "🎯 Deploying to $org_name/$repo_name..."
    echo "================================================"
    
    # Check if generated README exists
    readme_file="/Users/Mea/code/github-ecosystem/ecosystem-central-command/generated-readmes/${repo_name}-README.md"
    
    if [ ! -f "$readme_file" ]; then
        echo "❌ Generated README not found: $readme_file"
        ((failure_count++))
        echo ""
        continue
    fi
    
    echo "✅ README file found ($(wc -c < "$readme_file") characters)"
    
    # Get current README SHA
    echo "🔍 Getting current README information..."
    sha=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
        "https://api.github.com/repos/$org_name/$repo_name/contents/README.md" | \
        grep '"sha"' | head -1 | sed 's/.*"sha": *"\([^"]*\)".*/\1/')
    
    if [ -z "$sha" ]; then
        echo "📝 No existing README found - will create new one"
        sha_param=""
    else
        echo "✅ Found existing README (SHA: ${sha:0:7}...)"
        sha_param=", \"sha\": \"$sha\""
    fi
    
    # Encode content to base64
    echo "🔄 Encoding content for GitHub API..."
    encoded_content=$(base64 -i "$readme_file" | tr -d '\n')
    
    # Create JSON payload
    echo "📝 Creating API payload..."
    cat > /tmp/github_payload_${repo_name}.json << EOF
{
  "message": "🚀 Phase 2A: Deploy enhanced README with Universal Management\\n\\n✨ Enhanced with:\\n- Comprehensive Overview section\\n- Professional presentation\\n- Navigation links and structure\\n- Technology stack details\\n\\n🤖 Auto-generated by Universal README Management\\n📋 Phase 2A Personal Hub Rollout",
  "content": "$encoded_content"$sha_param
}
EOF
    
    echo "🚀 Deploying to GitHub..."
    
    # Deploy using curl
    response=$(curl -s -X PUT \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Content-Type: application/json" \
        -d @/tmp/github_payload_${repo_name}.json \
        "https://api.github.com/repos/$org_name/$repo_name/contents/README.md")
    
    # Check if deployment was successful
    if echo "$response" | grep -q '"commit"'; then
        echo "✅ SUCCESS! README deployed to $org_name/$repo_name"
        echo "🌐 View at: https://github.com/$org_name/$repo_name"
        commit_sha=$(echo "$response" | grep '"sha"' | head -1 | sed 's/.*"sha": *"\([^"]*\)".*/\1/')
        echo "📊 Commit SHA: ${commit_sha:0:7}..."
        ((success_count++))
    else
        echo "❌ Deployment failed for $org_name/$repo_name"
        echo "Response: $response"
        ((failure_count++))
    fi
    
    # Clean up
    rm -f /tmp/github_payload_${repo_name}.json
    echo ""
    
    # Small delay between deployments to respect API rate limits
    sleep 2
done

echo "📊 PHASE 2A ROLLOUT SUMMARY"
echo "============================"
echo "Total Repositories: $total_repos"
echo "✅ Successful Deployments: $success_count"
echo "❌ Failed Deployments: $failure_count"
echo ""

if [ $success_count -eq $total_repos ]; then
    echo "🎉 Phase 2A Rollout: COMPLETE SUCCESS!"
    echo "🚀 All Personal Hub repositories now have enhanced READMEs"
    echo "📋 Ready for Phase 2B: Cross-Organizational Deployment"
    echo ""
    echo "🔗 Your enhanced repositories:"
    echo "- https://github.com/DevPersonalHub/external-learning-platforms (✅ Already deployed)"
    echo "- https://github.com/DevPersonalHub/portfolio-website"
    echo "- https://github.com/DevPersonalHub/technical-showcase"
    echo "- https://github.com/DevPersonalHub/learning-projects"
else
    echo "⚠️ Phase 2A Rollout completed with some issues"
    echo "📋 Please review failed deployments and retry if needed"
fi